# -*- coding: utf-8 -*-
"""01_Variable_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ob4Du52guNWLSj0h3od-dqXoydPBtcK5

1. Create a variable named pi and store the value 22/7 in it. Now check the data type of this variable.
"""

pi = 22 / 7
print(pi)
type(pi)

"""2. Create a variable called for and assign it a value 4. See what happens and find out the reason behind the behavior that you see**.**"""

for = 4

#for is a keyword.

"""3. Store the principal amount, rate of interest, and time in different variables and then calculate the Simple Interest for 3 years**.**"""

p_amount = float(input("Enter the principal amount: "))
r_interest = float(input("Enter the rate of interest: "))
time = float(input("Enter time in years: "))
simple_interest = (p_amount * r_interest * time) / 100
print("Simple Interest: ", simple_interest)

